version: '3'
services:
  app:
    container_name: election-frontend-production
    image: docker.pkg.github.com/esc-chula/election-frontend/election-frontend-production:latest
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=shared'
      - 'traefik.http.routers.election-frontend-production.entrypoints=websecure'
      - 'traefik.http.routers.election-frontend-production.rule=Host(`elect.esc.eng.chula.ac.th`)'
      - 'traefik.http.routers.election-frontend-production.tls=true'
      - 'traefik.http.routers.election-frontend-production.tls.certresolver=myhttpchallenge'
    networks:
      - shared
networks:
  shared:
    external:
      name: shared
