name: deploy-staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [dev]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: whoan/docker-build-with-cache-action@v5
        name: Build Docker image
        with:
          username: bombnp
          password: '${{ github.token }}'
          registry: docker.pkg.github.com
          image_name: 'esc-chula/election-frontend/election-frontend-staging'

      - uses: appleboy/ssh-action@master
        name: Deploy to VM
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          host: ${{ env.VM_HOST }}
          username: ${{ env.VM_USER }}
          password: ${{ env.VM_PASS }}
          port: ${{ env.VM_PORT }}
          envs: GITHUB_TOKEN
          script: |
            set -e

            WORKDIR=election-frontend-staging
            rm -rf $WORKDIR

            git clone -b dev https://.:$GITHUB_TOKEN@github.com/esc-chula/election-frontend $WORKDIR

            docker login docker.pkg.github.com -u "bombnp" -p "$GITHUB_TOKEN"
            docker pull docker.pkg.github.com/esc-chula/election-frontend/election-frontend-staging:latest

            docker-compose --project-name=$WORKDIR -f $WORKDIR/docker-compose.yml stop
            docker-compose --project-name=$WORKDIR -f $WORKDIR/docker-compose.yml up -d

            rm -rf $WORKDIR
